openlayer_test/web_test/Controllers/Table2AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Openlayer_test.TESTDB;
using Openlayer_test.TESTDB.Interface;
using Openlayer_test.TESTDB.EF;
using web_test.Models;
using System.IO;

namespace web_test.Controllers
{
    public class Table2AdminController : Controller
    {
        private ITable2Repository _db = new Table2Repository();

        //
        // GET: /Table2Admin/

        public ActionResult Index()
        {
            var table2 = _db.GetAll();
            return View(table2.ToList());
        }

        //
        // GET: /Table2Admin/Details/5

        public ActionResult Details(int id = 0)
        {
            var table2 = _db.GetOne(id);
            if (table2 == null)
            {
                return HttpNotFound();
            }
            return View(table2);
        }

        //
        // GET: /Table2Admin/Create

        public ActionResult Create()
        {
            var village_model = new VillageRepository();
            ViewBag.VillageID = new SelectList(village_model.GetAll(null), "VillageID", "VillageName");
            return View();
        }

        //
        // POST: /Table2Admin/Create

        [HttpPost]
        public ActionResult Create(Openlayer_test.TESTDB.Table2 table2)
        {
            if (ModelState.IsValid)
            {
                _db.Create(table2);
                return RedirectToAction("Index");
            }
            var village_model = new VillageRepository();
            ViewBag.VillageID = new SelectList(village_model.GetAll(null), "VillageID", "VillageName", table2.VillageID);
            return View(table2);
        }

        //
        // GET: /Table2Admin/Edit/5

        public ActionResult Edit(int id = 0)
        {
            var table2 = _db.GetOne(id);
            if (table2 == null)
            {
                return HttpNotFound();
            }
            var village_model = new VillageRepository();
            ViewBag.VillageID = new SelectList(village_model.GetAll(null), "VillageID", "VillageName", table2.VillageID);
            return View(table2);
        }

        //
        // POST: /Table2Admin/Edit/5

        [HttpPost]
        public ActionResult Edit(Openlayer_test.TESTDB.Table2 table2)
        {
            if (ModelState.IsValid)
            {
                // db.Entry(table2).State = EntityState.Modified;
                _db.Update(table2);
                return RedirectToAction("Index");
            }
            var village_model = new VillageRepository();
            ViewBag.VillageID = new SelectList(village_model.GetAll(null), "VillageID", "VillageName", table2.VillageID);
            return View(table2);
        }

        //
        // GET: /Table2Admin/Delete/5

        public ActionResult Delete(int id = 0)
        {
            var table2 = _db.GetOne(id);
            if (table2 == null)
            {
                return HttpNotFound();
            }
            return View(table2);
        }

        //
        // POST: /Table2Admin/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            _db.Delete(id);
            return RedirectToAction("Index");
        }

        public ActionResult Download(int id = 0)
        {
            var table2 = _db.GetOne(id);
            if (table2 == null)
            {
                return HttpNotFound();
            }
            string file_path = table2.RawFile.Replace(@"H:\RAW\RSImage\UAV\Ortho\", "~/Archive/RAW/");
            file_path = Server.MapPath(file_path.Replace("\\", "/"));
            string filename = System.IO.Path.GetFileName(file_path);
            System.IO.Stream iStream = new System.IO.FileStream(file_path, FileMode.Open, FileAccess.Read, FileShare.Read);

            return File(iStream, "image/tif", filename);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

openlayer_test/web_test/Views/Table2Admin/Create.cshtml
@model Openlayer_test.TESTDB.Table2

@{
    ViewBag.Title = "Create";
}


<div class="container">
        <div class="row">

            <div class="col-md-6 well">
@using (Html.BeginForm("Create", "Table2Admin", FormMethod.Post, new { @role = "form", @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>New Table2</legend>

        <div class="form-group">
            @Html.LabelFor(model => model.RawFile, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.RawFile, new { @class = "form-control", placeholder = "RawFile", AutoComplete = "On", tabindex = "1" })
                @Html.ValidationMessageFor(model => model.RawFile)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnviFile, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.EnviFile, new { @class = "form-control", placeholder = "EnviFile", AutoComplete = "On", tabindex = "2" })
                @Html.ValidationMessageFor(model => model.EnviFile)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TileFile, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.TileFile, new { @class = "form-control", placeholder = "TileFile", AutoComplete = "On", tabindex = "3" })
                @Html.ValidationMessageFor(model => model.TileFile)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lon, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Lon, new { @class = "form-control", placeholder = "Lon", AutoComplete = "On", tabindex = "4" })
                @Html.ValidationMessageFor(model => model.Lon)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lat, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Lat, new { @class = "form-control", placeholder = "Lat", AutoComplete = "On", tabindex = "5" })
                @Html.ValidationMessageFor(model => model.Lat)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LeftGeo, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.LeftGeo, new { @class = "form-control", placeholder = "LeftGeo", AutoComplete = "On", tabindex = "6" })
                @Html.ValidationMessageFor(model => model.LeftGeo)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RightGeo, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.RightGeo, new { @class = "form-control", placeholder = "RightGeo", AutoComplete = "On", tabindex = "6" })
                @Html.ValidationMessageFor(model => model.RightGeo)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TopGeo, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.TopGeo, new { @class = "form-control", placeholder = "TopGeo", AutoComplete = "On", tabindex = "6" })
                @Html.ValidationMessageFor(model => model.TopGeo)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BottomGeo, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.BottomGeo, new { @class = "form-control", placeholder = "BottomGeo", AutoComplete = "On", tabindex = "7" })
                @Html.ValidationMessageFor(model => model.BottomGeo)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Resolution, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Resolution, new { @class = "form-control", placeholder = "Resolution", AutoComplete = "On", tabindex = "8" })
                @Html.ValidationMessageFor(model => model.Resolution)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Year, new { @class = "form-control", placeholder = "Year", AutoComplete = "On", tabindex = "9" })
                @Html.ValidationMessageFor(model => model.Year)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Month, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Month, new { @class = "form-control", placeholder = "Month", AutoComplete = "On", tabindex = "10" })
                @Html.ValidationMessageFor(model => model.Month)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Day, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Day, new { @class = "form-control", placeholder = "Day", AutoComplete = "On", tabindex = "11" })
                @Html.ValidationMessageFor(model => model.Day)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DisName, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DisName, new { @class = "form-control", placeholder = "DisName", AutoComplete = "On", tabindex = "12" })
                @Html.ValidationMessageFor(model => model.DisName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VillageID, "Village", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownList("VillageID", String.Empty)
                @Html.ValidationMessageFor(model => model.VillageID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Basin, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Basin, new { @class = "form-control", placeholder = "Basin", AutoComplete = "On", tabindex = "14" })
                @Html.ValidationMessageFor(model => model.Basin)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subbasinna, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Subbasinna, new { @class = "form-control", placeholder = "Subbasinna", AutoComplete = "On", tabindex = "15" })
                @Html.ValidationMessageFor(model => model.Subbasinna)
            </div>
        </div>

       <div class="col-md-12 text-right"><input type="submit" class="btn btn-primary" value="Create" /></div>
    </fieldset>
}
</div></div></div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

openlayer_test/web_test/Views/Table2Admin/Delete.cshtml
@model Openlayer_test.TESTDB.Table2

@{
    ViewBag.Title = "Delete";
}


<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Table2</legend>
    <table class="table table-bordered table-nonfluid" style="width:50%">
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.RawFile)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.RawFile)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.EnviFile)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.EnviFile)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.TileFile)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.TileFile)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.Lon)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.Lon)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.Lat)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.Lat)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.LeftGeo)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.LeftGeo)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.RightGeo)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.RightGeo)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.TopGeo)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.TopGeo)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.BottomGeo)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.BottomGeo)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.Resolution)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.Resolution)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.Year)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.Year)</td>
        </tr>
        <tr>
            <th class="active">
            @Html.DisplayNameFor(model => model.Month)
            </th>
            <td class="col-md-9">
            @Html.DisplayFor(model => model.Month)
            </td>
        </tr>

        <tr>
            <th class="active">
            @Html.DisplayNameFor(model => model.Day)
            </th>
            <td class="col-md-9">
            @Html.DisplayFor(model => model.Day)
            </td>
        </tr>

        <tr>
            <th class="active">
            @Html.DisplayNameFor(model => model.DisName)
            </th>
            <td class="col-md-9">
            @Html.DisplayFor(model => model.DisName)
            </td>
        </tr>

        <tr>
            <th class="active">
            @Html.DisplayNameFor(model => model.Village.VillageName)
            </th>
            <td class="col-md-9">
            @Html.DisplayFor(model => model.Village.VillageName)
            </td>
        </tr>

        <tr>
            <th class="active">
            @Html.DisplayNameFor(model => model.Basin)
            </th>
            <td class="col-md-9">
            @Html.DisplayFor(model => model.Basin)
            </td>
        </tr>

        <tr>
            <th class="active">
            @Html.DisplayNameFor(model => model.Subbasinna)
            </th>
            <td class="col-md-9">
            @Html.DisplayFor(model => model.Subbasinna)
            </td>
        </tr>
    </table>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

openlayer_test/web_test/Views/Table2Admin/Details.cshtml
@model Openlayer_test.TESTDB.Table2

@{
    ViewBag.Title = "Details";
}


<fieldset>
    <legend>Table2</legend>

    <table class="table table-bordered table-nonfluid" style="width:50%">
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.RawFile)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.RawFile)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.EnviFile)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.EnviFile)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.TileFile)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.TileFile)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.Lon)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.Lon)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.Lat)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.Lat)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.LeftGeo)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.LeftGeo)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.RightGeo)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.RightGeo)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.TopGeo)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.TopGeo)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.BottomGeo)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.BottomGeo)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.Resolution)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.Resolution)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.Year)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.Year)</td>
        </tr>
        <tr>
            <th class="active">
            @Html.DisplayNameFor(model => model.Month)
            </th>
            <td class="col-md-9">
            @Html.DisplayFor(model => model.Month)
            </td>
        </tr>

        <tr>
            <th class="active">
            @Html.DisplayNameFor(model => model.Day)
            </th>
            <td class="col-md-9">
            @Html.DisplayFor(model => model.Day)
            </td>
        </tr>

        <tr>
            <th class="active">
            @Html.DisplayNameFor(model => model.DisName)
            </th>
            <td class="col-md-9">
            @Html.DisplayFor(model => model.DisName)
            </td>
        </tr>

        <tr>
            <th class="active">
            @Html.DisplayNameFor(model => model.Village.VillageName)
            </th>
            <td class="col-md-9">
            @Html.DisplayFor(model => model.Village.VillageName)
            </td>
        </tr>

        <tr>
            <th class="active">
            @Html.DisplayNameFor(model => model.Basin)
            </th>
            <td class="col-md-9">
            @Html.DisplayFor(model => model.Basin)
            </td>
        </tr>

        <tr>
            <th class="active">
            @Html.DisplayNameFor(model => model.Subbasinna)
            </th>
            <td class="col-md-9">
            @Html.DisplayFor(model => model.Subbasinna)
            </td>
        </tr>
    </table>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Table2ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

openlayer_test/web_test/Views/Table2Admin/Edit.cshtml
@model Openlayer_test.TESTDB.Table2

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
<div class="container">
        <div class="row">
            <div class="col-md-6 well">
@using (Html.BeginForm("Edit", "Table2Admin", FormMethod.Post, new { @role = "form", @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Edit for Table1 (@Model.Table2ID)</legend>

        @Html.HiddenFor(model => model.Table2ID)

        <div class="form-group">
            @Html.LabelFor(model => model.RawFile, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.RawFile, new { @class = "form-control", placeholder = "RawFile", AutoComplete = "On", tabindex = "1" })
            @Html.ValidationMessageFor(model => model.RawFile)
        </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnviFile, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.EnviFile, new { @class = "form-control", placeholder = "EnviFile", AutoComplete = "On", tabindex = "2" })
            @Html.ValidationMessageFor(model => model.EnviFile)
        </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TileFile, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.TileFile, new { @class = "form-control", placeholder = "TileFile", AutoComplete = "On", tabindex = "3" })
            @Html.ValidationMessageFor(model => model.TileFile)
        </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lon, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Lon, new { @class = "form-control", placeholder = "Lon", AutoComplete = "On", tabindex = "4" })
            @Html.ValidationMessageFor(model => model.Lon)
        </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lat, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Lat, new { @class = "form-control", placeholder = "Lat", AutoComplete = "On", tabindex = "5" })
            @Html.ValidationMessageFor(model => model.Lat)
        </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LeftGeo, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.LeftGeo, new { @class = "form-control", placeholder = "LeftGeo", AutoComplete = "On", tabindex = "6" })
            @Html.ValidationMessageFor(model => model.LeftGeo)
        </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RightGeo, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.RightGeo, new { @class = "form-control", placeholder = "RightGeo", AutoComplete = "On", tabindex = "7" })
            @Html.ValidationMessageFor(model => model.RightGeo)
        </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TopGeo, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.TopGeo, new { @class = "form-control", placeholder = "TopGeo", AutoComplete = "On", tabindex = "8" })
            @Html.ValidationMessageFor(model => model.TopGeo)
        </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BottomGeo, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.BottomGeo, new { @class = "form-control", placeholder = "BottomGeo", AutoComplete = "On", tabindex = "9" })
            @Html.ValidationMessageFor(model => model.BottomGeo)
        </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Resolution, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Resolution, new { @class = "form-control", placeholder = "Resolution", AutoComplete = "On", tabindex = "10" })
            @Html.ValidationMessageFor(model => model.Resolution)
        </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Year, new { @class = "form-control", placeholder = "Year", AutoComplete = "On", tabindex = "11" })
            @Html.ValidationMessageFor(model => model.Year)
        </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Month, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Month, new { @class = "form-control", placeholder = "Month", AutoComplete = "On", tabindex = "12" })
            @Html.ValidationMessageFor(model => model.Month)
        </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Day, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Day, new { @class = "form-control", placeholder = "Day", AutoComplete = "On", tabindex = "13" })
            @Html.ValidationMessageFor(model => model.Day)
        </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DisName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.DisName, new { @class = "form-control", placeholder = "DisName", AutoComplete = "On", tabindex = "14" })
            @Html.ValidationMessageFor(model => model.DisName)
        </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VillageID, "Village", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownList("VillageID", String.Empty)
            @Html.ValidationMessageFor(model => model.VillageID)
        </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Basin, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Basin, new { @class = "form-control", placeholder = "Basin", AutoComplete = "On", tabindex = "16" })
            @Html.ValidationMessageFor(model => model.Basin)
        </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subbasinna, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Subbasinna, new { @class = "form-control", placeholder = "Subbasinna", AutoComplete = "On", tabindex = "17" })
            @Html.ValidationMessageFor(model => model.Subbasinna)
        </div>
        </div>

        <div class="col-md-12 text-right"><input type="submit" class="btn btn-primary" value="Save" /></div>
    </fieldset>
}
</div></div></div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}