openlayer_test/web_test/Controllers/TableAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Openlayer_test.TESTDB;
using Openlayer_test.TESTDB.Interface;
using Openlayer_test.TESTDB.EF;
using web_test.Models;

namespace web_test.Controllers
{
    public class TableAdminController : Controller
    {
        private ITable1Repository _db = new Table1Repository();

        //
        // GET: /TableAdmin/

        public ActionResult Index()
        {
            var table1 = _db.GetAll();
            return View(table1.ToList());
        }

        //
        // GET: /TableAdmin/Details/5

        public ActionResult Details(int id = 0)
        {
            var table1 = _db.GetOne(id);
            if (table1 == null)
            {
                return HttpNotFound();
            }
            return View(table1);
        }

        //
        // GET: /TableAdmin/Create

        public ActionResult Create()
        {
            var village_model = new VillageRepository();
            ViewBag.VillageID = new SelectList(village_model.GetAll(null), "VillageID", "VillageName");
            return View();
        }

        //
        // POST: /TableAdmin/Create

        [HttpPost]
        public ActionResult Create(Openlayer_test.TESTDB.Table1 table1)
        {
            if (ModelState.IsValid)
            {
                _db.Create(table1);
                return RedirectToAction("Index");
            }
            var village_model = new VillageRepository();
            ViewBag.VillageID = new SelectList(village_model.GetAll(null), "VillageID", "VillageName", table1.VillageID);
            return View(table1);
        }

        //
        // GET: /TableAdmin/Edit/5

        public ActionResult Edit(int id = 0)
        {
            var table1 = _db.GetOne(id);
            if (table1 == null)
            {
                return HttpNotFound();
            }
            var village_model = new VillageRepository();
            ViewBag.VillageID = new SelectList(village_model.GetAll(null), "VillageID", "VillageName", table1.VillageID);
            return View(table1);
        }

        //
        // POST: /TableAdmin/Edit/5

        [HttpPost]
        public ActionResult Edit(Openlayer_test.TESTDB.Table1 table1)
        {
            if (ModelState.IsValid)
            {
                // db.Entry(table1).State = EntityState.Modified;
                _db.Update(table1);
                return RedirectToAction("Index");
            }
            var village_model = new VillageRepository();
            ViewBag.VillageID = new SelectList(village_model.GetAll(null), "VillageID", "VillageName", table1.VillageID);
            return View(table1);
        }

        //
        // GET: /TableAdmin/Delete/5

        public ActionResult Delete(int id = 0)
        {
            var table1 = _db.GetOne(id);
            if (table1 == null)
            {
                return HttpNotFound();
            }
            return View(table1);
        }

        //
        // POST: /TableAdmin/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {   
            _db.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

openlayer_test/web_test/Views/TableAdmin/Create.cshtml
@model Openlayer_test.TESTDB.Table1

@{
    ViewBag.Title = "Create";
}

<div class="container">
        <div class="row">

            <div class="col-md-6 well">
@using (Html.BeginForm("Create", "TableAdmin", FormMethod.Post, new { @role = "form", @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>New Table1</legend>
        
        

        <div class="form-group">
            @Html.LabelFor(model => model.PlanYear, new { @class = "col-md-2 control-label" })
        
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.PlanYear, new { @class = "form-control", placeholder = "PlanYear", AutoComplete = "On", tabindex = "1" })
                @Html.ValidationMessageFor(model => model.PlanYear)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SUBBASINNA, new { @class = "col-md-2 control-label" })
        
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SUBBASINNA, new { @class = "form-control", placeholder = "SUBBASINNA", AutoComplete = "On", tabindex = "2" })
                @Html.ValidationMessageFor(model => model.SUBBASINNA)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VillageID, "Village", new { @class = "col-md-2 control-label" })
        
            <div class="col-md-10">
                @Html.DropDownList("VillageID", String.Empty)
                @Html.ValidationMessageFor(model => model.VillageID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DisName, new { @class = "col-md-2 control-label" })
        
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DisName, new { @class = "form-control", placeholder = "DisName", AutoComplete = "On", tabindex = "4" })
                @Html.ValidationMessageFor(model => model.DisName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.X, new { @class = "col-md-2 control-label" })
        
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.X, new { @class = "form-control", placeholder = "X", AutoComplete = "On", tabindex = "5" })
                @Html.ValidationMessageFor(model => model.X)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Y, new { @class = "col-md-2 control-label" })
        
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Y, new { @class = "form-control", placeholder = "Y", AutoComplete = "On", tabindex = "6" })
                @Html.ValidationMessageFor(model => model.Y)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lon, new { @class = "col-md-2 control-label" })
        
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Lon, new { @class = "form-control", placeholder = "Lon", AutoComplete = "On", tabindex = "7" })
                @Html.ValidationMessageFor(model => model.Lon)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lat, new { @class = "col-md-2 control-label" })
        
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Lat, new { @class = "form-control", placeholder = "Lat", AutoComplete = "On", tabindex = "8" })
                @Html.ValidationMessageFor(model => model.Lat)
            </div>
        </div>
        <div class="col-md-12 text-right"><input type="submit" class="btn btn-primary" value="New" /></div>
    </fieldset>
}
</div></div></div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

openlayer_test/web_test/Views/TableAdmin/Delete.cshtml
@model Openlayer_test.TESTDB.Table1

@{
    ViewBag.Title = "Delete";
}

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Table1</legend>
    <table class="table table-bordered table-nonfluid" style="width:50%">
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.PlanYear)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.PlanYear)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.SUBBASINNA)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.SUBBASINNA)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.Village.VillageName)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.Village.VillageName)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.DisName)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.DisName)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.X)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.X)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.Y)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.Y)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.Lon)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.Lon)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.Lat)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.Lat)</td>
        </tr>
    </table>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

openlayer_test/web_test/Views/TableAdmin/Details.cshtml
@model Openlayer_test.TESTDB.Table1

@{
    ViewBag.Title = "Details";
}


<fieldset>
    <legend>Table1</legend>
    <table class="table table-bordered table-nonfluid" style="width:50%">
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.PlanYear)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.PlanYear)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.SUBBASINNA)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.SUBBASINNA)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.Village.VillageName)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.Village.VillageName)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.DisName)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.DisName)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.X)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.X)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.Y)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.Y)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.Lon)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.Lon)</td>
        </tr>
        <tr>
            <th class="active">@Html.DisplayNameFor(model => model.Lat)</th>
            <td class="col-md-9">@Html.DisplayFor(model => model.Lat)</td>
        </tr>
    </table>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Table1ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

openlayer_test/web_test/Views/TableAdmin/Edit.cshtml
@model Openlayer_test.TESTDB.Table1

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
<div class="container">
        <div class="row">
            <div class="col-md-6 well">

@using (Html.BeginForm("Edit", "TableAdmin", FormMethod.Post, new { @role = "form", @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Edit for Table1 (@Model.Table1ID)</legend>

        @Html.HiddenFor(model => model.Table1ID)

        <div class="form-group">
            @Html.LabelFor(model => model.PlanYear, new { @class = "col-md-2 control-label" })
        
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.PlanYear, new { @class = "form-control", placeholder = "PlanYear", AutoComplete = "On", tabindex = "1" })
                @Html.ValidationMessageFor(model => model.PlanYear)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SUBBASINNA, new { @class = "col-md-2 control-label" })
        
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SUBBASINNA, new { @class = "form-control", placeholder = "SUBBASINNA", AutoComplete = "On", tabindex = "2" })
                @Html.ValidationMessageFor(model => model.SUBBASINNA)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VillageID, "Village", new { @class = "col-md-2 control-label" })
        
            <div class="col-md-10">
                @Html.DropDownList("VillageID", String.Empty)
                @Html.ValidationMessageFor(model => model.VillageID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DisName, new { @class = "col-md-2 control-label" })
        
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DisName, new { @class = "form-control", placeholder = "DisName", AutoComplete = "On", tabindex = "4" })
                @Html.ValidationMessageFor(model => model.DisName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.X, new { @class = "col-md-2 control-label" })
        
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.X, new { @class = "form-control", placeholder = "X", AutoComplete = "On", tabindex = "5" })
                @Html.ValidationMessageFor(model => model.X)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Y, new { @class = "col-md-2 control-label" })
        
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Y, new { @class = "form-control", placeholder = "Y", AutoComplete = "On", tabindex = "6" })
                @Html.ValidationMessageFor(model => model.Y)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lon, new { @class = "col-md-2 control-label" })
        
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Lon, new { @class = "form-control", placeholder = "Lon", AutoComplete = "On", tabindex = "7" })
                @Html.ValidationMessageFor(model => model.Lon)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lat, new { @class = "col-md-2 control-label" })
        
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Lat, new { @class = "form-control", placeholder = "Lat", AutoComplete = "On", tabindex = "8" })
                @Html.ValidationMessageFor(model => model.Lat)
            </div>
        </div>

        <div class="col-md-12 text-right"><input type="submit" class="btn btn-primary" value="Save" /></div>
        
    </fieldset>
}
</div></div></div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

openlayer_test/web_test/Views/TableAdmin/Index.cshtml
@model IEnumerable<Openlayer_test.TESTDB.Table1>

@{
    ViewBag.Title = "Index";
}

<h2>Table 1</h2>

<table class="table table-bordered table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PlanYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SUBBASINNA)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Village.VillageName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DisName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.X)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Y)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lat)
        </th>
        <th>@Html.ActionLink("Create New", "Create")</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PlanYear)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SUBBASINNA)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Village.VillageName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DisName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.X)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Y)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lat)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Table1ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.Table1ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Table1ID })
        </td>
    </tr>
}

</table>